version: '3.8'
services:
  actual-comdirect:
    image: ghcr.io/davidanderlohr/actual-comdirect:latest
    ports:
      - "5007:3000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./cache:/app/cache
    restart: unless-stopped
